# Generated by Django 4.2.11 on 2024-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmotionTracker', '0004_alter_feedback_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion_level', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('analyzed_emotion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
